/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufc.poo.petshop.Funcionarios;

/**
 *
 * @author Mateus
 */
public class MenuVeterinario extends javax.swing.JFrame {

    /**
     * Creates new form MenuBanhistas
     */
    public MenuVeterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        btnListaBanhistas = new javax.swing.JButton();
        btnReaAgendamento = new javax.swing.JButton();
        btnViewAgendamento = new javax.swing.JButton();
        btnExcAgendamento = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulo.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        titulo.setText("Menu Veterinário");

        subtitulo.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        subtitulo.setText("Selecione o que deseja fazer");

        btnCadastro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnCadastro.setText("Cadastro");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnListaBanhistas.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnListaBanhistas.setText("Lista de Veterinários");
        btnListaBanhistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaBanhistasActionPerformed(evt);
            }
        });

        btnReaAgendamento.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnReaAgendamento.setText("Realizar Agendamento");
        btnReaAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaAgendamentoActionPerformed(evt);
            }
        });

        btnViewAgendamento.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnViewAgendamento.setText("Visualizar Agendamentos");
        btnViewAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAgendamentoActionPerformed(evt);
            }
        });

        btnExcAgendamento.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnExcAgendamento.setText("Excluir Agendamento");
        btnExcAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcAgendamentoActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(subtitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastro)
                                .addGap(29, 29, 29)
                                .addComponent(btnListaBanhistas)
                                .addGap(18, 18, 18)
                                .addComponent(btnViewAgendamento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReaAgendamento)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcAgendamento)
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnVoltar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnListaBanhistas)
                    .addComponent(btnViewAgendamento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReaAgendamento)
                    .addComponent(btnExcAgendamento))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Form1 a = new Form1();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        CadastroVet c1 = new CadastroVet();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnListaBanhistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaBanhistasActionPerformed
        ListaVet c1 = new ListaVet();
        c1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaBanhistasActionPerformed

    private void btnReaAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaAgendamentoActionPerformed
        RealizarAngVet a = new RealizarAngVet();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReaAgendamentoActionPerformed

    private void btnViewAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAgendamentoActionPerformed
        ExibirAgeVet a = new ExibirAgeVet();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewAgendamentoActionPerformed

    private void btnExcAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcAgendamentoActionPerformed
        ExcluirAgeVet a = new ExcluirAgeVet();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnExcAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBanhistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBanhistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBanhistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBanhistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBanhistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnExcAgendamento;
    private javax.swing.JButton btnListaBanhistas;
    private javax.swing.JButton btnReaAgendamento;
    private javax.swing.JButton btnViewAgendamento;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
