/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufc.poo.petshop.Interfaces;

import br.ufc.poo.petshop.Funcionarios.Form1;

/**
 *
 * @author caiop
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1nameMenu = new javax.swing.JLabel();
        buttonCadCliente = new javax.swing.JButton();
        buttonCadFunc = new javax.swing.JButton();
        buttonVerClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1nameMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1nameMenu.setText("Menu Principal");

        buttonCadCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonCadCliente.setText("Cadastrar Cliente");
        buttonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadClienteActionPerformed(evt);
            }
        });

        buttonCadFunc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonCadFunc.setText("Menu Funcionários");
        buttonCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadFuncActionPerformed(evt);
            }
        });

        buttonVerClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonVerClientes.setText("Visualizar Clientes");
        buttonVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1nameMenu)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonCadCliente)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCadFunc)
                        .addGap(18, 18, 18)
                        .addComponent(buttonVerClientes)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1nameMenu)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCadFunc)
                    .addComponent(buttonVerClientes)
                    .addComponent(buttonCadCliente))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadClienteActionPerformed
        // TODO add your handling code here:
        Interface cadCliente = new Interface();
        cadCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCadClienteActionPerformed

    private void buttonCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadFuncActionPerformed
        // TODO add your handling code here:
        Form1 form = new Form1();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonCadFuncActionPerformed

    private void buttonVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerClientesActionPerformed
        // TODO add your handling code here:
        ExibirDocumentoTxt clientes = new ExibirDocumentoTxt();
        clientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVerClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadCliente;
    private javax.swing.JButton buttonCadFunc;
    private javax.swing.JButton buttonVerClientes;
    private javax.swing.JLabel jLabel1nameMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


}
