/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufc.poo.petshop.Funcionarios;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Mateus
 */
public class RealizarAngTos extends javax.swing.JFrame {

    /**
     * Creates new form RealizarAng
     */
    public RealizarAngTos() {
        initComponents();
        int numTos = 0;
        try (BufferedReader leitor = new BufferedReader(new FileReader("numTos.txt"))) {
            String linha;
            while ((linha = leitor.readLine()) != null) {
                numTos = Integer.parseInt(linha);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        Funcionario[] f = new Funcionario[numTos];
        for(int i = 0;i<numTos;i++){
        f[i] = new Funcionario();
        }
        try (BufferedReader leitor = new BufferedReader(new FileReader("funcionario.txt"))) {
            String linha;
            int contador2 = 0;
            while ((linha = leitor.readLine()) != null) {
                String[] palavras = linha.split(":");
                int contador = 0;
                int teste = Integer.parseInt(palavras[0]);
                if(teste == 1){
                for(String palavra : palavras){
                        if (contador == 0){
                            int tipo = Integer.parseInt(palavra);
                            f[contador2].setTipo(tipo);
                            contador++;
                        } else if(contador == 1){
                            f[contador2].setNome(palavra);
                            contador++;
                        } else if(contador == 2){
                            int idade = Integer.parseInt(palavra);
                            f[contador2].setIdade(idade);
                        }
                }}
                if(teste == 1){
                contador2++;
                }
            }
            
                
        } catch (IOException e) {
            e.printStackTrace();
        }
        for (int i = 0;i < numTos;i++){
            listaTos.addItem(f[i].getNome());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        listaTos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        btnReaAng = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setText("Realizar Agendamento Tosador");

        listaTos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        listaTos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Data:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Hora:");

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnReaAng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReaAng.setText("Realizar Agendamento");
        btnReaAng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaAngActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(listaTos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnReaAng)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnVoltar))
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titulo)
                .addGap(30, 30, 30)
                .addComponent(listaTos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReaAng)
                    .addComponent(btnVoltar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReaAngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaAngActionPerformed
        int numTos = 0;
        try (BufferedReader leitor = new BufferedReader(new FileReader("numTos.txt"))) {
            String linha;
            while ((linha = leitor.readLine()) != null) {
                numTos = Integer.parseInt(linha);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        Funcionario[] f = new Funcionario[numTos];
        for(int i = 0;i<numTos;i++){
        f[i] = new Funcionario();
        }
        try (BufferedReader leitor = new BufferedReader(new FileReader("funcionario.txt"))) {
            String linha;
            int contador2 = 0;
            while ((linha = leitor.readLine()) != null) {
                String[] palavras = linha.split(":");
                int contador = 0;
                int teste = Integer.parseInt(palavras[0]);
                if(teste == 1){
                for(String palavra : palavras){
                        if (contador == 0){
                            int tipo = Integer.parseInt(palavra);
                            f[contador2].setTipo(tipo);
                            contador++;
                        } else if(contador == 1){
                            f[contador2].setNome(palavra);
                            contador++;
                        } else if(contador == 2){
                            int idade = Integer.parseInt(palavra);
                            f[contador2].setIdade(idade);
                        }
                }}
                if(teste == 1){
                contador2++;
                }
            }
            
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        Agendamento a = new Agendamento();
        String data = txtData.getText();
        String hora = txtHora.getText();
        String nome = f[listaTos.getSelectedIndex()].getNome();
        a.fazAgendamentoTos(data, hora, nome);
        txtData.setText("");
        txtHora.setText("");
        
        
    }//GEN-LAST:event_btnReaAngActionPerformed

    private void listaTosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTosActionPerformed
        int numTos = 0;
        try (BufferedReader leitor = new BufferedReader(new FileReader("numTos.txt"))) {
            String linha;
            while ((linha = leitor.readLine()) != null) {
                numTos = Integer.parseInt(linha);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        Funcionario[] f = new Funcionario[numTos];
        for(int i = 0;i<numTos;i++){
        f[i] = new Funcionario();
        }
        try (BufferedReader leitor = new BufferedReader(new FileReader("funcionario.txt"))) {
            String linha;
            int contador2 = 0;
            while ((linha = leitor.readLine()) != null) {
                String[] palavras = linha.split(":");
                int contador = 0;
                int teste = Integer.parseInt(palavras[0]);
                if(teste == 1){
                for(String palavra : palavras){
                        if (contador == 0){
                            int tipo = Integer.parseInt(palavra);
                            f[contador2].setTipo(tipo);
                            contador++;
                        } else if(contador == 1){
                            f[contador2].setNome(palavra);
                            contador++;
                        } else if(contador == 2){
                            int idade = Integer.parseInt(palavra);
                            f[contador2].setIdade(idade);
                        }
                }}
                if(teste == 1){
                contador2++;
                }
            }
            
                
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_listaTosActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuTosador m1 = new MenuTosador();
        m1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarAng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarAng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarAng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarAng.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarAng().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReaAng;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> listaTos;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
